#!/usr/bin/env bash

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/trpi422/.sdkman"
[[ -s "/Users/trpi422/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/trpi422/.sdkman/bin/sdkman-init.sh"

