#!/usr/bin/env bash

_do_completions() {
    #if [ -n "$BASH_COMPLETION_VERSINFO" ]
    #then
    #    return
    #fi

    # force completion to always rerun in subshell
    unset BASH_COMPLETION_VERSINFO

    local completion_location
    if is_mac
    then
        completion_location="/usr/local/etc/profile.d/bash_completion.sh"
        if ! [ -r "$completion_location" ]
        then
            completion_location="/opt/homebrew/etc/profile.d/bash_completion.sh"
        fi
    else
        completion_location="/home/linuxbrew/.linuxbrew/etc/profile.d/bash_completion.sh"
    fi

    [[ -r "${completion_location}" ]] && . "${completion_location}"
}

_do_completions
unset _do_completions
