#!/usr/bin/env bash

export _FZF_USUAL_OPTS="\
--walker-skip=.git,node-modules,.venv \
--preview='{ [ -d {} ] && fd --hidden . {}; } || { [ -f {} ] && bat --color=always -r :500 {}; } || { [ -e {} ] && ls -l {}; } || { var={}; [ \"\${var}\" = \"\${var// /}\" ] && [ -n \"\${!var}\" ] && echo \"\${!var}\"; } || :' \
"
export FZF_COMPLETION_DIR_OPTS="$_FZF_USUAL_OPTS --walker dir,follow,hidden"
export FZF_COMPLETION_PATH_OPTS="$_FZF_USUAL_OPTS --walker file,dir,follow,hidden"
export FZF_ALT_C_OPTS="$_FZF_USUAL_OPTS"
export FZF_CTRL_T_OPTS="$_FZF_USUAL_OPTS"
export FZF_CTRL_R_OPTS="
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"

_fzf_comprun() {
  local command=$1
  shift

  case "$command" in
    #cd)           fzf                                      "$@" ;;
    export|unset) fzf --preview "eval 'echo \$'{}"         "$@" ;;
    ssh)          fzf --preview 'dig {}'                   "$@" ;;
    *)            fzf                                      "$@" ;;
  esac
}
export -f _fzf_comprun

type -t fzf &>/dev/null && eval "$(fzf --bash)"
