#!/usr/bin/env bash

if [ -z "${PYENV_ROOT}" ]
then
  export PYENV_ROOT="${HOME}/.pyenv"
fi
export PATH="$PYENV_ROOT/bin:$PATH"

function pyenv_completion {
    eval "$(pyenv init --path)"
    eval "$(pyenv init -)"
}
export -f pyenv_completion

if ! dotfiles_skip pyenv-completion
then
    pyenv_completion
fi
