#!/usr/bin/env bash

export PIPENV_VENV_IN_PROJECT=1

function pipenv_completion {
    #eval "$(_PIPENV_COMPLETE=bash_source pipenv)"
    eval "$(SHLVL=2 _PIPENV_COMPLETE=bash_source pipenv)"
}
export -f pipenv_completion

if ! dotfiles_skip pipenv-completion
then
    pipenv_completion
fi
