#!/usr/bin/env bash

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
#[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"

function pyenv_completion {
    type -t pyenv &>/dev/null && eval "$(pyenv init - --no-rehash)"
}
export -f pyenv_completion

if ! dotfiles_skip pyenv-completion
then
    pyenv_completion
fi
