#!/usr/bin/env bash

[ -n "$CARGO_HOME" ] && [ -f "$CARGO_HOME/env" ] && source "$CARGO_HOME/env"
[ -n "$(type -t rustup)" ] && {
    eval "$(rustup completions bash)"
    eval "$(rustup completions bash cargo)"
}
