#!/usr/bin/env bash

export PIPENV_VENV_IN_PROJECT=1
if [ -f "$PYENV_ROOT/shims/python" ]
then
    export PIPENV_PYTHON="$PYENV_ROOT/shims/python"
fi

function pipenv_completion {
    local pipenv_completion_cache="$HOME/.pipenv_completion.cache"
    if ! [ -e "$pipenv_completion_cache" ]
    then
        SHLVL=2 _PIPENV_COMPLETE=bash_source pipenv > "$pipenv_completion_cache"
    fi
    #eval "$(_PIPENV_COMPLETE=bash_source pipenv)"
    #eval "$(SHLVL=2 _PIPENV_COMPLETE=bash_source pipenv)"
    . "$pipenv_completion_cache"
}
export -f pipenv_completion

if ! dotfiles_skip pipenv-completion
then
    pipenv_completion
fi
