#!/usr/bin/env bash

if command -v nvim &> /dev/null
then
    export EDITOR=nvim
else
    export EDITOR=vim
fi

export PATH="$HOME/dotbin:/usr/local/sbin:$PATH"

export DEVHOME="${HOME}"
export FOLDER_DEV="${DEVHOME}/development"
export FOLDER_DEVTOOLS="${FOLDER_DEV}/tools"
export FOLDER_DEVREPOS="${FOLDER_DEV}/repos"
export FOLDER_DEVCONFIG="${FOLDER_DEV}/config"

function finder_show_all_files {
    local set=$1

    if [ -z "${set}" ]
    then
        echo "Usage:" >&2
        echo "  finder_show_all_files true|false" >&2
        return 1
    fi

    defaults write com.apple.finder AppleShowAllFiles ${set}
    echo "Reload finder with \"killall Finder\"" >&2
}
export -f finder_show_all_files
