#!/usr/bin/env bash

export _proxyr_proxies="https_proxy HTTPS_PROXY http_proxy HTTP_PROXY all_proxy ALL_PROXY"
export _proxyr_no_proxies="no_proxy NO_PROXY"

function proxyr {
  if [ -z "$2" ]
  then
    echo "USAGE : proxyr PROXY NO_PROXY" >&2
    return 1
  fi

  local proxy=$1
  local no_proxy_hosts=$2

  local proxy_var
  for proxy_var in $_proxyr_proxies
  do
    eval "export $proxy_var=$proxy"
  done

  for proxy_var in $_proxyr_no_proxies
  do
    eval "export $proxy_var=$no_proxy_hosts"
  done
}
export -f proxyr

function proxyr_unset {
  local proxy
  for proxy in $_proxyr_proxies $_proxyr_no_proxies
  do
    eval "unset $proxy"
  done
}
export -f proxyr_unset

# Ensures proxies are prefixed with the requested scheme
function _proxy_ensure_scheme {
  if [ -z "$1" ]
  then
    echo "USAGE : _proxy_ensure_scheme SCHEME" >&2
    return 1
  fi

  local proxy_scheme=$1
  local proxy
  for proxy in $_proxyr_proxies $_proxyr_no_proxies
  do
    eval "[[ -z \${${proxy}} || \${${proxy}} == ${proxy_scheme}* ]] || export ${proxy}=${proxy_scheme}://\${${proxy}}"
  done
}
export -f _proxy_ensure_scheme

# prints the commands for exporting proxy variables (e.g. for copypasta/eval)
function proxyenv {
  local proxy
  for proxy in $_proxyr_proxies $_proxyr_no_proxies
  do
    echo ${proxy}=$(eval echo \$$proxy)
  done
}
export -f proxyenv

function disable_proxies {
  export NO_PROXY="*"
  export no_proxy="$NO_PROXY"
}
export -f disable_proxies
