#!/usr/bin/bash

# Updates configuration following a brew upgrade docker
function docker_reup {
  # sudo rsync -avu /Applications/Docker.app/Contents/Library/LaunchServices/com.docker.vmnetd /Library/PrivilegedHelperTools/com.docker.vmnetd
  # sudo rsync -avu ~/.dotenv-etc/com.docker.vmnetd.plist /Library/LaunchDaemons/com.docker.vmnetd.plist
  # sudo chown root:wheel /Library/PrivilegedHelperTools/com.docker.vmnetd
  # sudo chown root:wheel /Library/LaunchDaemons/com.docker.vmnetd.plist
  # sudo chmod 544 /Library/PrivilegedHelperTools/com.docker.vmnetd
  # sudo chmod 644 /Library/LaunchDaemons/com.docker.vmnetd.plist
  # sudo launchctl load /Library/LaunchDaemons/com.docker.vmnetd.plist
  # sudo xattr -r -d com.apple.quarantine /Applications/Docker.app

  sudo xattr -r -d com.apple.quarantine /Applications/Docker.app
  sudo /Applications/Docker.app/Contents/MacOS/Docker --install-privileged-components
  open /Applications/Docker.app

  docker_autocompletion
}
export -f docker_reup

# Adds docker completion scripts to bash completion
function docker_autocompletion {
  for prog in docker{,-compose}
  do
    local source=/Applications/Docker.app/Contents/Resources/etc/${prog}.bash-completion
    local dest=/usr/local/etc/bash_completion.d/${prog}

    if [ -f $source ]
    then
      rm -f $dest
      ln -s $source $dest
    else
      echo WARNING: Completion for $prog not found at $source >&2
    fi
  done
}
export -f docker_autocompletion
