#!/usr/bin/env bash

export _repo_parents="${FOLDER_DEVREPOS}"
export _repo_max_depth=3

function repo_stat {
    local parent repo repo_dir
    for parent in ${_repo_parents}
    do
        while read repo
        do
            if [ -d "${repo}/.git" ]
            then
                repo_dir=${repo#$parent}
                repo_dir=${repo_dir#/}
                echo -e "${_fmt_lc}==>${_fmt_x} ${_fmt_dw}[${parent}]${_fmt_x} ${_fmt_lc}${repo_dir}${_fmt_x}" \
                    | sed "s|${HOME}|~|g"
                git -C "$repo" status --short --branch
            fi
        done < <(find "$parent" \
            -type d \
            -mindepth 1 \
            -maxdepth $_repo_max_depth \
            ! -path "*/.git/*" \
            ! -path "*/src/*" \
            ! -path "*/node_modules/*" \
            ! -path "*/.gradle/*" \
            ! -path "*/build/*" \
            ! -path "*/packages/*" \
            | sort)
    done
}
export -f repo_stat
