#!/usr/bin/env bash

function jwt_decode {
    local token=$1

    if [ -z "$token" ]
    then
        echo "Please provide a JWT as the first argument" >&2
        return
    fi

    local line
    tr '.' '\n' <<< $token \
        | awk '
            FNR < 3 {
                pad=length($1) % 4;
                printf $1;
                if (pad > 0) {
                    printf substr("==", 0, 4 - pad)
                }
                printf "\n"
            }
        ' \
        | while read line
        do
            base64 -D <<< "$line" | jq .
        done
}
export -f jwt_decode
