#!/usr/bin/env bash

export VAULT_PROFILE=""
export VAULT_COMPANY="troweprice"
export _vault_prefix=".vault."
export _vault_suffix=""
export _vault_none="none"
export _vault_default_profile=0
export _vault_token_file=${HOME}/.vault-token
export _vault_info_file=${HOME}/.vault-info

function _vault_files {
    ls ${HOME}/${_vault_prefix}${1}${_vault_suffix}
}
export -f _vault_files

function _vault_environments {
    local env_prefix=$1
    _vault_files "${env_prefix}*" 2>/dev/null | sed "s/[^[:space:]]*\/${_vault_prefix}\([^[:space:]]*\)${_vault_suffix}/\1/g"
}
export -f _vault_environments

# Usage:
#   vaultprofile [ <profile ID> | <profile name> | <env> ]
#
# e.g.
#   vaultprofile 1
#   vaultprofile dev
#   vaultprofile dev.org.role
#
function vaultprofile {
    local environment=${1}
    local environments=(${_vault_none} $(_vault_environments))
    local environment_count=${#environments[@]}

    if [[ -z "${environment}" ]] || [[ "${environment}" =~ ^[0-9]+$ && $((environment_count-environment-1)) -lt 0 ]] || [[ ! "${environment}" =~ ^[0-9]+$ && ! " ${environments[@]} " =~ " ${environment} " ]]
    then
        echo "Please provide an existing environment id/name:" >&2
        local i=0
        for e in ${environments[@]}
        do
            if [[ "${VAULT_PROFILE}" = "${e}" ]] || [ -z "${VAULT_PROFILE}" -a "${i}" -eq 0 ]
            then
                printf -- "- %-4s ${_fmt_g}${e}${_fmt_x}\n" "(${i})" >&2
            else
                printf -- "- %-4s ${e}\n" "(${i})" >&2
            fi
            i=$((i+1))
        done
        return
    fi

    if [[ "${environment}" =~ ^(${_vault_none}|0)$ ]]
    then
        unset VAULT_PROFILE
        unset VAULT_ADDR
        unset VAULT_ROLE_ID
        unset VAULT_SECRET_ID
        unset VAULT_ENV
        unset VAULT_ORG
        unset VAULT_ROLE
    else
        local env

        if [[ "${environment}" =~ ^[0-9]+$ ]]
        then
            env=${environments[environment]}
        else
            env=${environment}
        fi

        . ${HOME}/${_vault_prefix}${env}${_vault_suffix}
        export VAULT_PROFILE=${env}

        _vault_set_env_token ${VAULT_ENV}
    fi
}
export -f vaultprofile

function _vault_set_env_token {
    local env=$1
    local vault_env_token_file=${HOME}/.vault-token.${env}

    if [ -z "${env}" ]
    then
        return
    fi

    if [ ! -r ${vault_env_token_file} ]
    then
        vault_login
    else
        mv ${_vault_token_file} ${HOME}/.vault-token.bak
        cp ${vault_env_token_file} ${_vault_token_file}
    fi
}
export -f _vault_set_env_token

function vault_url {
    local env=${1,,}
    if [ -z "${env}" -o "prod" = "${env}" ]
    then
        echo "https://vault.${VAULT_COMPANY}.io:8200"
    else
        echo "https://vault.${env}.${VAULT_COMPANY}.io:8200"
    fi

}
export -f vault_url

function vault_setup {
    local env=${1,,}
    local org=${2,,}
    local role=${3,,}
    # TODO trap and reset
    local vault_old_addr=${VAULT_ADDR}
    local vault_old_env=${VAULT_ENV}
    local vault_url=$(vault_url ${env})

    export VAULT_ADDR=${vault_url}
    export VAULT_ENV=${env}
    _vault_set_env_token ${env}

    local vault_file="${HOME}/${_vault_prefix}${env}"

    cat << EOF > ${vault_file}
export VAULT_ADDR=${vault_url}
export VAULT_ENV=${env}
EOF

    if [ -n "${role}" ]
    then
        vault_file="${HOME}/${_vault_prefix}${env}.${org}.${role}"
        local vault_role_id=$(vault_roleid ${org} ${role} | awk '$1=="role_id" {print $2}')
        [ -z "$vault_role_id" ] && return 1
        local vault_secret_id=$(vault_secretid ${org} ${role} | awk '$1=="secret_id" {print $2}')
        [ -z "$vault_secret_id" ] && return 2

        cat << EOF > ${vault_file}
export VAULT_ADDR=${vault_url}
export VAULT_ROLE_ID=${vault_role_id}
export VAULT_SECRET_ID=${vault_secret_id}
export VAULT_ENV=${env}
export VAULT_ORG=${org}
export VAULT_ROLE=${role}
EOF
    fi

    export VAULT_ADDR=${vault_old_addr}
    _vault_set_env_token ${vault_old_env}
}
export -f vault_setup

function _vault_role_token {
    vault \
        write \
        -format=json \
        auth/approle/${VAULT_COMPANY}/${VAULT_ORG}/login \
        role_id=$VAULT_ROLE_ID \
        secret_id=$VAULT_SECRET_ID \
        | jq -r .auth.client_token
}
export -f _vault_role_token

vaultprofile "${_vault_default_profile}"

function vault_login {
    mv ${_vault_token_file} ${HOME}/.vault-token.bak

    local username=$(sed 's/.*\\//' <<< $USER)

    vault login -method=ldap -path=ldap/${VAULT_COMPANY}/unix username=${username}

    if [ -n "${VAULT_ENV}" ]
    then
        local vault_env_token_file=${HOME}/.vault-token.${VAULT_ENV}

        cp ${_vault_token_file} ${vault_env_token_file}
    fi
}
export -f vault_login

# Usage:
#   vault_roleid <org> <role>
#
# e.g.
#   vault_roleid kings admin
#
function vault_roleid {
    if [ -z "$2" ]
    then
        echo "Usage: vault_roleid <project> <component" >&2
        return 1
    fi

    vault read auth/approle/${VAULT_COMPANY}/${1}/role/${2}/role-id
}
export -f vault_roleid

# Usage:
#   vault_secretid <org> <role>
#
# e.g.
#   vault_secretid kings admin
#
function vault_secretid {
    if [ -z "$2" ]
    then
        echo "Usage: vault_secretid <project> <component" >&2
        return 1
    fi

    vault write -f auth/approle/${VAULT_COMPANY}/${1}/role/${2}/secret-id

    printf "%s===\n=== %sYou must update your VAULT_SECRET_ID export!%s\n===\n%s" $_fmt_g $_fmt_x $_fmt_g $_fmt_x
}
export -f vault_secretid

function vault_as_role {
    if [ -z "${VAULT_PROFILE}" ]
    then
        echo "Please select a vault profile by running vaultprofile" >&2
        return 1
    fi

    local command="$@"

    VAULT_TOKEN=$(_vault_role_token) vault ${command}
}
export -f vault_as_role

function _vaultinfo_file {
    echo "${_vault_info_file}.${VAULT_ENV}"
}
export -f _vaultinfo_file

function _vault_policies {
    vault token lookup -format json | jq -r '.data.policies[]'
}
export -f _vault_policies

function _vault_policy_approles {
    local policy=$1
    vault policy read $policy \
        | awk '/^path.*approle/{print $2}' \
        | sed 's/"//g;s/[/*]*$//' \
        | sort \
        | uniq
}
export -f _vault_policy_approles

function _vault_policy_approles_resolved {
    local policy=$1
    local approle_paths=$(_vault_policy_approles $policy)
    local path
    for path in $approle_paths
    do
        local org=$(sed 's/\/role.*//;s/.*\///' <<< $path)
        if [[ "$path" =~ /role$ ]]
        then
            local roles=$(vault list $path 2>/dev/null | tail -n+3)
            local role
            for role in $roles
            do
                echo "$org:$role"
            done
        else
            echo "$org:$(sed 's/.*\/role\///;s/\/.*-id$//' <<< "$path")"
        fi
    done \
        | sort \
        | uniq
}
export -f _vault_policy_approles_resolved

function vaultinfo_refresh {
    if [ -z "${VAULT_ENV}" ]
    then
        echo "A valid vault profile must be set - try running \"vaultprofile\"" >&2
        return 1
    fi

    local infofile
    infofile=$(_vaultinfo_file)

    local policy policies
    policies=$(_vault_policies)
    for policy in $policies
    do
        printf "%-100s" "Refreshing from ${_fmt_bd}${_fmt_g}${policy}${_fmt_x} policy..." >&2
        echo "ZZZ $policy"
        vault policy read $policy
        echo "${_fmt_bd}${_fmt_g}Done${_fmt_x}" >&2
    done \
        | awk '
            /ZZZ/                        { policy=$2 }
            $1 == "path"                 { printf policy " " $2 }
            $1 ~ /(capabilities|policy)/ { $1=""; $2=""; print $0 }
        ' > $infofile
}
export -f vaultinfo_refresh

function vaultinfo_refresh_all {
    local env
    for env in dev sit stage prod
    do
        (
            echo "${_fmt_bd}Refreshing for ${_fmt_c}${env}:${_fmt_x}"
            _vault_use_env $env
            vaultinfo_refresh
        )
    done
}
export -f vaultinfo_refresh_all

function vaultinfo {
    if [ -z "${VAULT_ENV}" ]
    then
        echo "A valid vault profile must be set - try running \"vaultprofile\"" >&2
        return 1
    fi

    local infofile
    infofile=$(_vaultinfo_file)

    if [ ! -e $infofile ]
    then
        echo "No vault info has been fetched for the current environment - try running \"vaultinfo_refresh\"" >&2
        return 1
    fi

    {
        echo "ZZZ Approles:"
        echo "ZZZ"
        awk '$2 ~ /^"auth\/approle/ { $1=""; print }' $infofile | sort

        echo "ZZZ"
        echo "ZZZ Amazon STS:"
        echo "ZZZ"
        awk '$2 ~ /\/sts\// { $1=""; print }' $infofile | sort

        echo "ZZZ"
        echo "ZZZ DB Creds:"
        echo "ZZZ"
        awk '$2 ~ /^"database/ { $1=""; print }' $infofile | sort

        echo "ZZZ"
        echo "ZZZ Secrets:"
        echo "ZZZ"
        awk '$2 ~ /^"secret/ { $1=""; print }' $infofile | sort
    } \
        | sed 's/"//g' \
        | awk '
            $1 != "ZZZ" {
                path=$1
                $1=""
                printf ($0 ~ "create")  ? "c" : "-"
                printf ($0 ~ "write")   ? "w" : "-"
                printf ($0 ~ "read")    ? "r" : "-"
                printf ($0 ~ "update")  ? "u" : "-"
                printf ($0 ~ "delete")  ? "d" : "-"
                printf ($0 ~ "list")    ? "l" : "-"
                printf ($0 ~ "sudo")    ? "S" : "-"
                printf ($0 ~ "deny")    ? "D" : "-"
                printf " " path "\n"
            }
            $1 == "ZZZ" { $1=""; print $0 }
        '
}
export -f vaultinfo

function vault_setup_env {
    local env=$1

    (
        _vault_use_env $env

        local policy
        local disp_pol disp_role
        for policy in $(_vault_policies)
        do
            disp_pol=$(echo "${_fmt_bd}${_fmt_c}${policy}${_fmt_x}")
            local orgrole
            for orgrole in $(_vault_policy_approles_resolved "$policy")
            do
                disp_role=$(echo "${_fmt_bd}${orgrole}${_fmt_x}")

                printf "%-120s" "Setting up [${disp_pol}] ${disp_role}..."

                local org role
                read org role <<< "$(tr ':' ' ' <<< "$orgrole")"
                if ! vault_setup $env $org $role 2>/dev/null
                then
                    echo "${_fmt_bd}${_fmt_r}Failed"
                    echo "Try running \"vault_setup $env $org $role\" manually${_fmt_x}"
                else
                    echo "${_fmt_bd}${_fmt_g}Done${_fmt_x}"
                fi
            done
        done
    )
}
export -f vault_setup_env

function vault_setup_all {
    local env
    for env in dev sit stage prod
    do
        echo "${_fmt_bd}${_fmt_g}== Environment: ${env} ==${_fmt_x}"
        vault_setup_env "$env"
    done
}
export -f vault_setup_all

function _vault_use_env {
    local env="$1"

    _vault_ensure_env $env
    vaultprofile $env
    _vault_ensure_logged_in
}
export -f _vault_use_env

function _vault_ensure_env {
    local env="$1"

    local env_file=$(_vault_files $env)
    if [ ! -f "$env_file" ]
    then
        echo "${_fmt_bd}${_fmt_y}Setting up vaultprofile for new env...${_fmt_x}"
        vault_setup $env >/dev/null
    fi
}
export -f _vault_ensure_env

function _vault_ensure_logged_in {
    if ! vault token lookup &>/dev/null
    then
        echo "${_fmt_bd}${_fmt_y}Reauthenticating with environment...${_fmt_x}"
        vault_login >/dev/null
    fi
}
export -f _vault_ensure_logged_in

# completion
function _vaultprofile {
    local length=${#COMP_WORDS[@]}
    if [ $length -gt 2 ]
    then
        COMPREPLY=()
        return
    fi

    local profile_prefix=${COMP_WORDS[1]}
    local use_none=""
    [[ -z "${profile_prefix}" || "${_vault_none}" =~ ^${profile_prefix}.* ]] && use_none=${_vault_none}
    COMPREPLY=(${use_none} $(_vault_environments ${profile_prefix}))
}
export -f _vaultprofile
